### ISSUE TITLE
Request: kafka - add ability to create more partitions

### ISSUE THREAD

**Issue by karelbilek** [orlangure/gnomock#1031]
**Describe the bug**
Currently, you can create only topics with one partition.

All topics now have 1 partition and that's hard-coded.

**To Reproduce**
Create kafka with topics. They all have 1 partition, it's here in the code

https://github.com/orlangure/gnomock/blob/6bb416a0047040aa7c5ea726cd5e1263a9ad6459/preset/kafka/preset.go#L212

(After I get gnomock running, I will try to make a PR that will add this functionality)

**Comment by orlangure** [comment]
Hey @karelbilek and thank you for reporting this. It would be great if you could implement this, just like you did with a few other issues so far. Thanks for your work!

**Comment by karelbilek** [comment]
Thanks for merging all stuff so far! Now I am happy to use kafka here
