### ISSUE TITLE
Request: Support newer localstack versions

### ISSUE THREAD

**Issue by fspaniol** [orlangure/gnomock#1034]
Related to: https://github.com/orlangure/gnomock/pull/1012

As of now, we can't use `gnomock.Start` with the preset features because the healthcheck endpoints have been migrated to `_localstack/health`, and it's not even configurable from the outside.

**Comment by orlangure** [comment]
Hey @fspaniol and thank you for bringing this up. I have a pull request with a bunch of version upgrades. It should take care of supporting localstack up to 3.1.0

https://github.com/orlangure/gnomock/pull/1039
