### ISSUE TITLE
Implement MariaDB preset

### ISSUE THREAD

**Issue by orlangure** [orlangure/gnomock#52]
A short guide on implementing a new preset:
https://github.com/orlangure/gnomock/blob/master/CONTRIBUTING.md#new-presets

MySQL preset for inspiration:
https://github.com/orlangure/gnomock/tree/master/preset/mysql

The objective is to implement a new Preset that spins up MariaDB docker container, sets up its initial state (tables, data), waits for it to become ready and kills it in the end.

Please note that there are multiple steps required to create a new preset (see the guide above).
I'm here to help😼

**Comment by dusansimic** [comment]
Hi, I'd like to work on this one 😁.

**Comment by orlangure** [comment]
Hi @dusansimic,
Sure, go ahead, you already know how to do it 😼
Thank you!
