### ISSUE TITLE
Implement Cassandra preset

### ISSUE THREAD

**Issue by orlangure** [orlangure/gnomock#54]
A short guide on implementing a new preset:
https://github.com/orlangure/gnomock/blob/master/CONTRIBUTING.md#new-presets

MySQL preset for inspiration:
https://github.com/orlangure/gnomock/tree/master/preset/mysql

The objective is to implement a new Preset that spins up Cassandra docker container, sets up its initial state (user provided data), waits for it to become ready and kills it in the end.

Please note that there are multiple steps required to create a new preset (see the guide above).
I'm here to help 😼

**Comment by s-surineni** [comment]
Hi, Can I work on this issue?

**Comment by orlangure** [comment]
Hi @s-surineni, sure! Thank you.
Let me know if you need any help getting started.

**Comment by orlangure** [comment]
@albertoforcato, no, so far no updates from @s-surineni. Would you like to take over?
If not, I will get to it at some point.

**Comment by albertoforcato** [comment]
@orlangure It could be great!

**Comment by s-surineni** [comment]
Sorry, couldn't work on this. You can take over

**Comment by orlangure** [comment]
> It could be great!

@albertoforcato, which option would be great? You taking over the task, or me?😼

**Comment by orlangure** [comment]
Released in [v0.16.0](https://github.com/orlangure/gnomock/releases/tag/v0.16.0)
