### ISSUE TITLE
Request: Custom the image of preset

### ISSUE THREAD

**Issue by koolay** [orlangure/gnomock#565]
I can't see how to  custom the image of mysql.

**Comment by orlangure** [comment]
Hi @koolay,

If you need to provide the version of mysql image, use `mysql.WithVersion()` option when creating a new preset instance.

If you need to use a custom docker image for some reason (which may not work since it was never tested), you can use something like this:
```go
pp := mysql.Preset()
opts := pp.Options()
gnomock.StartCustom("custom-image", pp.Ports(), opts...)
```

**Comment by koolay** [comment]
@orlangure 

The default preset of mysql is not work on the mac m1.
I need to custom the image with `mysql/mysql-server:8.xxx-aarch64`.

**Comment by orlangure** [comment]
Thank you for raising this issue, I'm releasing a new version where mysql preset should work on both amd64 and arm64 architectures.
