### ISSUE TITLE
Allow to import messages from file/directly in RabbitMQ Preset

### ISSUE THREAD

**Issue by orlangure** [orlangure/gnomock#59]
RabbitMQ Preset is missing a key feature: automated and simplified message ingestion upon startup. See [Kafka preset](https://github.com/orlangure/gnomock/blob/master/preset/kafka/options.go#L22-L36) for example: 

```go
// WithMessages makes sure that these messages can be consumed during the test
// once the container is ready.
func WithMessages(messages ...Message) Option {
	return func(o *P) {
		o.Messages = append(o.Messages, messages...)
	}
}

// WithMessagesFile allows to load messages to be sent into Kafka from one or
// multiple files.
func WithMessagesFile(files string) Option {
	return func(o *P) {
		o.MessagesFiles = append(o.MessagesFiles, files)
	}
}
```

Implementing this feature should allow users to provide a text file with messages in JSON format, or specify message objects directly using `WithMessages` option. When RabbitMQ container is ready, these messages should be already ready to consume.

In this issue, an [`InitFunc`](https://github.com/orlangure/gnomock/blob/cb9088989e2d0f12271bad1f3a4d198433da0705/options.go#L30-L34) should be added to preset code. This function should be applied only when there are messages or message files, just like in Kafka.

Just like with any other preset development, please try to cover all the cases mentioned in [contribution guide](https://github.com/orlangure/gnomock/blob/master/CONTRIBUTING.md#new-presets).

**Comment by dusansimic** [comment]
Hi again 😀, I'd like to work on this one too.

**Comment by orlangure** [comment]
Thanks @dusansimic!
