### ISSUE TITLE
Configure golangci-lint to skip some linters in test files

### ISSUE THREAD

**Issue by orlangure** [orlangure/gnomock#72]
Right now, there is a bunch of `// nolint:funlen` or `// nolint:bodyclose` comments in various tests. These comments tell golangci-lint to exclude the marked tests from linter reports.

Instead of marking each test file separately, there is a configuration of golangci-lint that we can set once in `.golangci-lint.yaml`. This configuration should apply to all test files.

Linters that should be disabled for test files:
- bodyclose
- funlen
- gosec

**Comment by u5surf** [comment]
@orlangure 
Hi, Can I work on this issue?

**Comment by orlangure** [comment]
Hi @u5surf,
Sure, thank you!
