### ISSUE TITLE
Improve CircleCI builds (align with Github Actions)

### ISSUE THREAD

**Issue by orlangure** [orlangure/gnomock#74]
CircleCI builds: https://app.circleci.com/pipelines/github/orlangure/gnomock
CircleCI workflow configuration: https://github.com/orlangure/gnomock/blob/master/.circleci/config.yml

Github Actions configuration: https://github.com/orlangure/gnomock/blob/master/.github/workflows/test.yaml

## 
Github Actions is the primary CI platform of this project. But many use CircleCI, and up until now Gnomock didn't work (at least sometimes) there.

Since we used Github Actions for project builds, we kind of constantly verified that Gnomock worked in this environment. So, to ensure that Gnomock also works in CircleCI, the best way would to have similar workflows in all supported platforms.

The goal of this task is to have all presets, core functionality, and SDKs (currently only python) tested in CircleCI builds, just like we have in Github Actions. The separation of jobs does not have to be the same, but it would be better if builds were relatively fast.

**Comment by 0b01001110** [comment]
Hello, maintainers!
Can I work on this issue?

**Comment by orlangure** [comment]
Hi @0b01001110, of course, thank you!
Let me know if you have any questions.
