### ISSUE TITLE
Bug: verifying module: checksum mismatch in dependecy

### ISSUE THREAD

**Issue by visteras** [orlangure/gnomock#770]
**Describe the bug**
I get `checksum mismatch` when download `github.com/docker/distribution@v2.8.0+incompatible` when use `go get github.com/orlangure/gnomock`

**To Reproduce**
Just `go get github.com/orlangure/gnomock`

**Expected behavior**
Successfully go get operation

**Screenshots**
![image](https://user-images.githubusercontent.com/4115292/211072822-37b285c4-64a6-45db-b14d-61f4d9fa86f3.png)

**System (please complete the following information):**
 - OS: Windows 10 Pro
 - Version v0.24.0
 - Docker 20.10.21

**Additional context**
I can't find tag `v2.8.0+incompatible`  in `github.com/docker/distribution` but find `v2.8.0` and download files not equals in repo with tag:
![image](https://user-images.githubusercontent.com/4115292/211073325-c7dcb5ad-7916-422d-be8a-22727ce0a0ba.png)
![image](https://user-images.githubusercontent.com/4115292/211073455-3af63f1d-8fcd-405e-8db8-3895f07ebfef.png)

P.S. `go get github.com/orlangure/gnomock@v0.19.0` are working

**Comment by orlangure** [comment]
Hi @visteras and thank you for the report.

I couldn't reproduce the issue you are having: I created a new Go project in an empty folder with `go mod init`, ran `go get github.com/orlangure/gnomock`, create a `main.go` file that uses gnomock, and executed it successfully.

I would suggest trying the same: making sure the import works in an isolated environment.
In your main project, I suggest running `go mod tidy`.

**Comment by visteras** [comment]
I try this and is not work(only 0.19.0 work)
You can use `go clean --modcache` for clean cache and retry reproduce?
In v0.19.0 this work, but 0.19.0 version use `github.com/docker/distribution@2.7.1`

**Comment by orlangure** [comment]
Hey @visteras, sorry for taking so long to reply.

I tried clearing go modules cache, creating a fresh new project, and importing gnomock into it. Everything worked as expected with the latest version.

I think the problem is not reproducible and you should look into the reason in your environment.
